# Generated by Django 2.2.6 on 2019-10-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='aritst',
            new_name='artist',
        ),
    ]
